include:
  - project: "gitlab/ci-templates"
    file: "/autodevops-ci.yml"

variables:
  DOTNET_SDK_VERSION: "5.0"
  DOTNET_RUNTIME_VERSION: "5.0"

stages:
  - prebuild
  - build
  - deploy

version:
  extends: .version
  stage: prebuild
  tags:
    - docker

warmer:
  extends: .kanikocache
  stage: prebuild
  tags:
    - docker

build:
  extends: .kanikobuild
  tags:
    - docker
  services: [ ]
  stage: build
  dependencies:
    - version

deploy:
  allow_failure: false
  image: registry.ubiquitous.no/gitlab/auto-deploy-image:latest
  stage: deploy
  tags:
    - kubernetes
  script:
    - auto-deploy check_kube_domain
    - pulumi_deploy
    - auto-deploy persist_environment_url
  dependencies:
    - version
    - build
  environment:
    name: production
    kubernetes:
      namespace: replicator

build_gcr:
  image:
    name: gcr.io/kaniko-project/executor:debug-v0.18.0
    entrypoint: [ "" ]
  script: >
    use_version
    mkdir -p ./cache && mv ./cache $(pwd)
    cat $GCR_ACCOUNT > /kaniko/.docker/config.json
    docker_repo=eu.gcr.io/$CI_PROJECT_PATH
    echo "Building Dockerfile in $repo_root to $docker_repo"
    echo "Tag $CI_APPLICATION_TAG, application version $APPLICATION_VERSION"
    dockerfilePath=$CI_PROJECT_DIR
    /kaniko/executor --cache=true \
      --cache-dir=$(pwd)/cache \
      --context $CI_PROJECT_DIR --dockerfile $dockerfilePath/Dockerfile \
      --destination $docker_repo:$CI_APPLICATION_TAG \
      --build-arg DOTNET_SDK_VERSION="$DOTNET_SDK_VERSION" \
      --build-arg DOTNET_RUNTIME_VERSION="$DOTNET_RUNTIME_VERSION" \
      --build-arg APPLICATION_VERSION="$APPLICATION_VERSION"
  stage: build
  only:
    - branches
    - tags
  cache:
    key: kaniko-cache
    paths:
      - ./cache/
