include:
  - project: "gitlab/ci-templates"
    file: "/autodevops-ci.yml"

variables:
  DOTNET_SDK_VERSION: "5.0"
  DOTNET_RUNTIME_VERSION: "5.0"

stages:
  - prebuild
  - build
  - deploy

version:
  extends: .version
  stage: prebuild
  tags:
    - docker

warmer:
  extends: .kanikocache
  stage: prebuild
  tags:
    - docker

build:
  extends: .kanikobuild
  tags:
    - docker
  services: [ ]
  stage: build
  dependencies:
    - version

deploy:
  allow_failure: false
  image: registry.ubiquitous.no/gitlab/auto-deploy-image:latest
  stage: deploy
  tags:
    - kubernetes
  script:
    - auto-deploy check_kube_domain
    - pulumi_deploy
    - auto-deploy persist_environment_url
  dependencies:
    - version
    - build
  environment:
    name: production
    kubernetes:
      namespace: replicator

build_gcr:
  image:
    name: gcr.io/kaniko-project/executor:debug-v0.18.0
    entrypoint: [ "" ]
  script:
    - |
      use_version
      mkdir -p ./cache && mv ./cache $(pwd)
      echo $GCR_ACCOUNT > /kaniko/secret.json
      export GOOGLE_APPLICATION_CREDENTIALS=/kaniko/secret.json
      cat <<EOF > /kaniko/.docker/config.json
      {
        "auths": {
          "$CI_REGISTRY": {
            "username": "$CI_REGISTRY_USER",
            "password": "$CI_REGISTRY_PASSWORD"
          }
        },
        "credHelpers": {
          "eu.gcr.io": "gcr"
        }
      }
      EOF
    - >
      /kaniko/executor --cache=true \
        --cache-dir=$(pwd)/cache \
        --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile \
        --destination eu.gcr.io/esc-platform-advocacy/$CI_PROJECT_PATH:latest \
        --build-arg DOTNET_SDK_VERSION="$DOTNET_SDK_VERSION" \
        --build-arg DOTNET_RUNTIME_VERSION="$DOTNET_RUNTIME_VERSION" \
        --build-arg APPLICATION_VERSION="$APPLICATION_VERSION"
  stage: build
  only:
    - branches
    - tags
  cache:
    key: kaniko-cache
    paths:
      - ./cache/
