config:
  es-replicator:app:
    Name: es-replicator
    Port: 5000
    SecretChecksum: null
    SecretName: null
    Tier: web
    Track: stable
  es-replicator:deploy:
    Image: null
    ImagePullSecret: gitlab-registry
    ImageTag: latest
    Namespace: replicator
    Release: production
    Replicas: 1
  es-replicator:gitlab:
    App: replicator
  es-replicator:ingress:
    Enabled: false
    Tls:
      Enabled: false
  es-replicator:prometheus:
    Metrics: true
    Path: /metrics
    Operator: true
  es-replicator:service:
    Enabled: true
    ExternalPort: 5000
    Type: ClusterIP
  es-replicator:env:
    - Name: EventStoreOptions__ClusterId
      Value: c0brjdirh41g7drr2i50
    - Name: SimulationOptions__Protocol
      Value: tcp
  
