apiVersion: v1
data:
  REPLICATOR_READER_PROTOCOL: {{ default "tcp" .Values.replicator.reader.protocol | quote }}
  REPLICATOR_READER_CONNECTIONSTRING: {{ .Values.replicator.reader.connectionString | quote }}
  REPLICATOR_SINK_PROTOCOL: {{ default "grpc" .Values.replicator.sink.protocol | quote }}
  REPLICATOR_SINK_CONNECTIONSTRING: {{ .Values.replicator.sink.connectionString | quote }}
  REPLICATOR_SCAVENGE: {{ default "true" .Values.replicator.scavenge | quote }}
  REPLICATOR_CHECKPOINT_PATH: "/data/checkpoint"
kind: ConfigMap
metadata:
  name: {{ template "replicator.fullname" . }}
  labels:
    app: {{ template "replicator.name" . }}
    chart: {{ template "replicator.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}