apiVersion: v1
data:
  "appsettings.yaml": |
    replicator:
{{ toYaml .Values.replicator | indent 6 }}
      checkpoint:
        path: "./checkpoint"
kind: ConfigMap
metadata:
  name: {{ template "replicator.fullname" . }}
  labels:
    app: {{ template "replicator.name" . }}
    chart: {{ template "replicator.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}