apiVersion: v1
data:
  replicator: |
{{ toYaml .Values.replicator | indent 4 }}
    checkpoint:
      path: "./checkpoint"
kind: ConfigMap
metadata:
  name: {{ template "replicator.fullname" . }}
  labels:
    app: {{ template "replicator.name" . }}
    chart: {{ template "replicator.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}