apiVersion: {{ template "deployment.apiVersion" . }}
kind: Deployment
metadata:
  name: {{ template "replicator.fullname" . }}
  labels:
    app: {{ template "replicator.name" . }}
    chart: {{ template "replicator.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    tier: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "replicator.name" . }}
      release: {{ .Release.Name }}
      tier: web
  template:
    metadata:
      labels:
        app: {{ template "replicator.name" . }}
        release: {{ .Release.Name }}
        tier: web
    spec:
      containers:
      - image: eu.gcr.io/esc-platform-advocacy/eventstore/replicator:latest
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
            scheme: HTTP
        name: {{ .Chart.Name }}
        ports:
        - containerPort: 5000
          name: web
        readinessProbe:
          httpGet:
            path: /ping
            port: 5000
            scheme: HTTP
        volumeMounts:
        - mountPath: /data
          name: {{ template "replicator.name" . }}
        - name: config-volume
          mountPath: /app/config
      imagePullSecrets: []
      terminationGracePeriodSeconds: 60
      volumes:
      - name: config-volume
        configMap:
          name: {{ template "replicator.fullname" . }}
      - name: {{ template "replicator.name" . }}
        persistentVolumeClaim:
          claimName: {{ template "replicator.fullname" . }}
