apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "replicator.fullname" . }}
  labels:
    app: {{ template "replicator.name" . }}
    chart: {{ template "replicator.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Mi
  {{ if .Values.pvc.storageClass }}
  storageClassName: {{ .Values.pvc.storageClass }}
  {{ end }}