{{ - if and .Values.prometheus.metrics .Values.prometheus.operator }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ template "replicator.fullname" . }}
  labels:
    app: {{ template "replicator.name" . }}
    chart: {{ template "replicator.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  endpoints:
  - interval: 15s
    path: /metrics
    port: web
  namespaceSelector:
    matchNames:
    - {{ .Release.Namespace }}
  selector:
    matchLabels:
      app: {{ template "replicator.name" . }}
      release: {{ .Release.Name }}
