baseURL: "https://replicator.eventstore.org"
languageCode: "en-GB"
title: "Event Store Replicator"
theme: "PaperMod"
paginate: 5

params:
  defaultTheme: auto
  displayFullLangName: true
  comments: false

  profileMode:
    enabled: false
    title: PaperMod
    imageUrl: "#"
    imageTitle: my image
    # imageWidth: 120
    # imageHeight: 120
    buttons:
      - name: Archives
        url: archives
      - name: Tags
        url: tags
  homeInfoParams:
    Title: "Replicator Docs"
    Content: >
      Welcome to the Event Store Replicator docs.
      
      - Lean about [available features](posts/features.md)
      - Ensure to check the [limitations](posts/limitations.md)
      - Deploy and run it [in Kubernetes](posts/kubernetes.md)