prometheus:
  metrics: false
  operator: false
replicator:
  reader:
    connectionString:
    protocol: tcp
  sink:
    connectionString:
    protocol: grpc
    concurrencyLimit: 1
    partitionCount: 1
  scavenge: true
    