prometheus:
  metrics: false
  operator: false
pvc:
  storageClass: null
terminationGracePeriodSeconds: 300
resources:
  limits:
    cpu: 1
    memory: 1Gi
  requests:
    cpu: 250m
    memory: 512Mi
replicator:
  reader:
    connectionString:
    protocol: tcp
  sink:
    connectionString:
    protocol: grpc
    partitionCount: 1
    bufferSize: 1000
  scavenge: true
  filters: []
  transform: null
    